pipeline:
  install:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile

  test:
    image: node:dubnium
    commands:
      - yarn test

  deploy:
    image: node:dubnium
    commands:
      - npm install netlify-cli
      - yarn clean
      - yarn build
      - netlify deploy --prod
