pipeline:
  install:
    image: node:dubnium
    commands:
      - yarn install --frozen-lockfile

  test:
    image: node:dubnium
    commands:
      - yarn test

  deploy:
    image: node:dubnium
    secrets:
      [
        basic_auth_password,
        basic_auth_username,
        gatsby_drupal_api,
        gatsby_drupal_site_folder,
        gatsby_initiatives_api,
        netlify_auth_token,
        netlify_site_id,
      ]
    commands:
      - yarn deploy
