pipeline:
  install:
    image: node:dubnium
    commands:
      - npm install netlify-cli
      - yarn install --frozen-lockfile

  test:
    image: node:dubnium
    commands:
      - yarn test

  deploy:
    image: node:dubnium
    secrets: [site_base_url, netlify_auth_token, netlify_site_id]
    commands:
      - yarn clean
      - yarn build
      - netlify deploy --prod
