module.exports = {
  defaultLangKey: 'en',
  // The `languages` list follows ECL spec. (splash page, language swticher, etc.)
  languages: [
    // { lang: 'bg', label: 'български' },
    // { lang: 'es', label: 'español' },
    // { lang: 'cs', label: 'čeština' },
    // { lang: 'da', label: 'dansk' },
    // { lang: 'de', label: 'Deutsch' },
    // { lang: 'et', label: 'eesti' },
    // { lang: 'el', label: 'ελληνικά' },
    { lang: 'en', label: 'English' },
    { lang: 'fr', label: 'français' },
    { lang: 'ga', label: 'Gaeilge' },
    // { lang: 'hr', label: 'hrvatski' },
    // { lang: 'it', label: 'italiano' },
    // { lang: 'lv', label: 'latviešu' },
    // { lang: 'lt', label: 'lietuvių' },
    // { lang: 'hu', label: 'magyar' },
    // { lang: 'mt', label: 'Malti' },
    // { lang: 'nl', label: 'Nederlands' },
    // { lang: 'pl', label: 'polski' },
    // { lang: 'pt', label: 'português' },
    // { lang: 'ro', label: 'română' },
    // { lang: 'sk', label: 'slovenčina' },
    // { lang: 'sl', label: 'slovenščina' },
    // { lang: 'fi', label: 'suomi' },
    // { lang: 'sv', label: 'svenska' },
  ],
};
