[build]
  functions = "api"

[[redirects]]
  # initiatives/open/details/2019/000010
  from = "/initiatives/:status/:action/:year/:number"
  to = " /initiative/:year/:month/:date/:slug"

[[redirects]]
  from = "/initiatives/*"
  to = "/initiative/"
  status = 200
  force = false
