const getCountriesTranslated = t => {
  return {
    al: t('Albania'),
    ad: t('Andorra'),
    am: t('Armenia'),
    at: t('Austria'),
    be: t('Belgium'),
    bg: t('Bulgaria'),
    es: t('Spain'),
    cz: t('Czech Republic'),
    cy: t('Cyprus'),
    da: t('Denmark'),
    de: t('Germany'),
    ee: t('Estonia'),
    gb: t('United Kingdom'),
    gr: t('Greece'),
    fr: t('France'),
    ga: t('Ireland'),
    hr: t('Croatia'),
    ie: t('Ireland'),
    it: t('Italia'),
    lv: t('Latvia'),
    lu: t('Luxembourg'),
    lt: t('Lithuania'),
    hu: t('Hungary'),
    mt: t('Malta'),
    nl: t('Netherlands'),
    pl: t('Poland'),
    pt: t('Portugal'),
    ro: t('Romania'),
    sk: t('Slovakia'),
    si: t('Slovenia'),
    fi: t('Finland'),
    se: t('Sweden'),
  };
};

export default getCountriesTranslated;
